<?php echo '<?php'; ?>


namespace <?php echo $namespace; ?>;

use Exception;

use Propel\Runtime\ActiveRecord\ActiveRecordInterface;
use Propel\Runtime\ActiveQuery\ModelCriteria;

/**
 * Class API is a static class for handling API requests generated by PropelJS.
 *
 * Do not edit this file; any changes will be overwritten the next time you
 * run `propel model:build`.
 *
 * See the documentation at https://github.com/AthensFramework/PropelJS
 */
class API {

    /** @var string */
    static $method;

    /** @var integer */
    static $resourceId;

    /** @var array */
    static $primaryKeys;

    /** @var array */
    static $primaryKey;

    /** @var string */
    static $resourceName;

    /** @var integer */
    static $resourceNamePathPosition;

    /** @var string */
    static $action;

    /** @var ModelCriteria */
    static $query;

    /** @var ActiveRecordInterface */
    static $resource;

    /** @var array */
    static $data;

    const ACTION_CREATE = 'CREATE';
    const ACTION_LIST = 'LIST';
    const ACTION_RETRIEVE = 'RETRIEVE';
    const ACTION_UPDATE = 'UPDATE';
    const ACTION_DESTROY = 'DESTROY';

    /**
    * @return string
    */
    protected static function getLocation()
    {
        return strtok($_SERVER['REQUEST_URI'], '?');
    }

    /**
     * @return string
     */
    public static function getMethod()
    {
        if (static::$method === null) {
            static::$method = $_SERVER['REQUEST_METHOD'];
        }
        return static::$method;
    }

    /**
     * @return string
     */
    public static function getResourceName()
    {
        if (static::$resourceName === null) {
            $path = explode('/', trim(static::getLocation(), '/'));

            static::$resourceName = $path[static::$resourceNamePathPosition];

        //    if (is_numeric(end($path)) === true) {
        //        array_pop($path);
        //    }

        //    static::$resourceName = array_pop($path);
        }
        return static::$resourceName;
    }


    /**
     * @return integer
     */
    public static function listPrimaryKeys($tableName)
    {
        if (static::$primaryKeys === null) {
            static::$primaryKeys = [
<?php foreach ($tablePks as $tableName => $pks) { ?>
                '<?= $tablePlurals[$tableName] ?>' => [<?php

foreach ($pks as $keyName => $keyType) {
    echo '\'', $keyName, '\' => \'', $keyType, '\',';
} ?>],
<?php } ?>
            ];
        }

        if ($tableName !== false) {
            return static::$primaryKeys[$tableName];
        } else {
            return static::$primaryKeys;
        }
    }

    /**
     * @return array
     */
    public static function getPrimaryKey()
    {
        if (static::$primaryKey === null) {
            $pks = static::listPrimaryKeys(static::getResourceName());
            $path = explode('/', trim(static::getLocation(), '/'));

            $i = 1;
            foreach($pks as $pk_column => $pk_type) {

                if (!isset($path[static::$resourceNamePathPosition + $i])) {
                    return null;
                }

                static::$primaryKey[$i-1] = $path[static::$resourceNamePathPosition + $i];

                $i++;
            }
        }

        return static::$primaryKey;
    }

    /**
     * @return array
     */
    public static function getData()
    {
        if (static::$data === null) {
            static::$data = json_decode(file_get_contents("php://input"), true);
        }
        return static::$data;
    }

    /**
    * @return string[]
    */
    public static function getQueryData()
    {
        return $_GET;
    }

    /**
     * @return string
     */
    public static function getAction()
    {
        $method = static::getMethod();

        $resourcePk = static::getPrimaryKey();

        if (static::$action === null) {
            if ($method === 'GET' && $resourcePk !== null) {
                static::$method = static::ACTION_RETRIEVE;
            } elseif ($method === 'GET') {
                static::$method = static::ACTION_LIST;
            } elseif ($method === 'POST' && $resourcePk === null) {
                static::$method = static::ACTION_CREATE;
            } elseif ($method === 'PUT' && $resourcePk !== null) {
                static::$method = static::ACTION_UPDATE;
            } elseif ($method === 'DELETE' && $resourcePk !== null) {
                static::$method = static::ACTION_DESTROY;
            } else {
                header("HTTP/1.0 405 Method Not Allowed");
                die("The method \"$method\" is not allowed, or is not allowed on this resource.");
            }
        }

        return static::$method;
    }

    /**
     * @return ModelCriteria
     */
    public static function getQueryOr404()
    {
        if (static::$query === null) {
            $resourceName = static::getResourceName();

            switch ($resourceName) {<?php foreach ($tablePlurals as $tableName => $tablePluralName) { ?>

                case '<?php echo $tablePluralName; ?>':
                    static::$query = <?php echo $tablePhpNames[$tableName]; ?>Query::create();
                    break;
<?php } ?>

                default:
                    header("HTTP/1.0 404 Not Found");
                    die("Resource type \"$resourceName\" not found.");
            }
        }

        return static::$query;
    }

    /**
     * @param ModelCriteria $query
     * @param $resourceId
     * @return ActiveRecordInterface
     */
    protected static function getResourceOr404(ModelCriteria $query)
    {

        if (static::$resource === null) {

            $pk = static::getPrimaryKey();

            static::$resource = $query->findPk(count($pk) > 1 ? $pk : $pk[0]);

            if (static::$resource === null) {
                header("HTTP/1.0 404 Not Found");
                die("Resource not found.");
            }
        }

        return static::$resource;
    }

    /**
     * @param ModelCriteria $query
     * @return string
     */
    protected static function createResource(ModelCriteria $query)
    {
        /** @var string $className */
        $className = $query->getTableMap()->getClassName();

        /** @var ActiveRecordInterface $resource */
        $resource = new $className();

        $resource->fromArray(static::getData());
        $resource->save();

        return json_encode($resource->toArray());
    }

    /**
    * @param ModelCriteria $query
    * @return string
    */
    protected static function listResources(ModelCriteria $query)
    {
        $queryData = static::getQueryData();

        foreach ($queryData as $columnName => $value) {
            if ($query->getTableMap()->hasColumnByPhpName($columnName) && trim($value) !== '') {
                $query->filterBy($columnName, $value);
            }
        }

        $queryData = array_merge(['offset' => 0, 'limit' => 25], $queryData);

        $query->offset($queryData['offset'])->limit($queryData['limit']);

        $queryDataNext = $queryData;
        $queryDataNext['offset'] += $queryData['limit'];

        $queryDataPrevious = $queryData;
        $queryDataPrevious['offset'] = max($queryData['offset'] - $queryData['limit'], 0);

        return json_encode(
            [
                'current' => static::getLocation() . '?' . http_build_query($queryData),
                'previous' => (int)$queryData['offset'] === 0 ?
                    null :
                    static::getLocation() . '?' . http_build_query($queryDataPrevious),
                'next' => static::getLocation() . '?' . http_build_query($queryDataNext),
                'data' => $query->find()->toArray()
            ]
            , JSON_UNESCAPED_SLASHES
        );
    }

    /**
     * Retrieves the given $resourceId within the given $query. Returns a JSON encoded
     * string.
     *
     * @param ModelCriteria $query
     * @param integer $resourceId
     * @return string
     */
    protected static function retrieveResource(ModelCriteria $query)
    {
        $resource = static::getResourceOr404($query);

        return json_encode($resource->toArray());
    }

    /**
     * Performs the update action on the given $resourceId within the given $query, using
     * the given $data. Returns a JSON encoded string.
     *
     * The array $data shall be an associative array of resource attribute key => value
     * pairs.
     *
     * @param ModelCriteria $query
     * @param integer       $resourceId
     * @param array         $data
     * @return string
     */
    protected static function updateResource(ModelCriteria $query)
    {
        $resource = static::getResourceOr404($query);
        $resource->fromArray(static::getData());
        $resource->save();

        return json_encode($resource->toArray());
    }

    /**
     * Performs the delete action on the given $resourceId within the given $query.
     *
     * @param ModelCriteria $query
     * @param $resourceId
     * @return string
     */
    protected static function deleteResource(ModelCriteria $query)
    {
        $resource = static::getResourceOr404($query);
        $resource->delete();

        return "{}";
    }

    /**
     * Handle the resource request identified by variables in $_SERVER.
     *
     * @return string
     * @throws Exception if ::getAction() identifies an unanticipated action.
     */
    public static function handle($resourceNamePathPosition) {

        static::$resourceNamePathPosition = $resourceNamePathPosition;
        $query = static::getQueryOr404();

        switch (static::getAction()) {
            case static::ACTION_LIST:
                return static::listResources($query);
            case static::ACTION_CREATE:
                return static::createResource($query);
            case static::ACTION_RETRIEVE:
                return static::retrieveResource($query);
            case static::ACTION_UPDATE:
                return static::updateResource($query);
            case static::ACTION_DESTROY:
                return static::deleteResource($query);
            default:
                throw new Exception("Encountered unexpected action type \"{static::getAction}\" in ::handle.");
        }
    }
}
